### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by muirp-owner**

### CODE REVIEW

**Comment by muirp-owner** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **muirp-owner**

If they are not already assigned, you can assign the PR to them by writing `/assign @muirp-owner` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/muirp/demo1/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by muirp-owner** [comment]
:star: PR built and available in a preview environment **muirp-demo1-pr-4** [here](http://demo1.jx-muirp-demo1-pr-4.35.187.164.124.nip.io)

**Review by deanesmith — APPROVED** [review]

**Comment by muirp-owner** [comment]
@pmuir: GitHub didn't allow me to request PR reviews from the following users: jstrachan.

Note that only [muirp members](https://github.com/orgs/muirp/people) and repo collaborators can review this PR, and authors cannot review their own PRs.

<details>

In response to [this](https://github.com/muirp/demo1/pull/4#issuecomment-449029166):

>/cc @jstrachan


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by muirp-owner** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/muirp/demo1/pull/4#pullrequestreview-185106516" title="Approved">deanesmith</a>*, *<a href="https://github.com/muirp/demo1/pull/4#issuecomment-449029378" title="LGTM">pmuir</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/muirp/demo1/blob/master/OWNERS)~~ [pmuir]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
